//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckPoint_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msgs
    {
        public int Id { get; set; }
        public string Msg { get; set; }
        public int Sender_User_Id { get; set; }
        public int Receiver_User_Id { get; set; }
        public int Pre_Msg_Id { get; set; }
    }
}
